### ISSUE TITLE
Widget or Golden Tests

### ISSUE THREAD

**Issue by mars3142** [md-siam/getx_clean_architecture#1]
I would like to see an example of widget and/or golden tests. This would be really helpful.

PS: Your widget_test.dart is a unit test and not widget test.

**Comment by md-siam** [comment]
"widget_test.dart" is the default test file provided when you create a new flutter application.

**Comment by md-siam** [comment]
That "widget_test.dart" is a default file generated by the flutter framework.

**Comment by mars3142** [comment]
> That "widget_test.dart" is a default file generated by the flutter framework.

But this won't help me, because I can't see any widget or golden tests. This should be added for reference.
